/********************************************************************
* CalibrationManagerDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error CalibrationManagerDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCalibrationManagerDict();
extern void G__cpp_setup_inheritanceCalibrationManagerDict();
extern void G__cpp_setup_typetableCalibrationManagerDict();
extern void G__cpp_setup_memvarCalibrationManagerDict();
extern void G__cpp_setup_globalCalibrationManagerDict();
extern void G__cpp_setup_memfuncCalibrationManagerDict();
extern void G__cpp_setup_funcCalibrationManagerDict();
extern void G__set_cpp_environmentCalibrationManagerDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/bender/Programs/GRSISpoon/include/CalibrationManager.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CalibrationManagerDictLN_TClass;
extern G__linked_taginfo G__CalibrationManagerDictLN_TBuffer;
extern G__linked_taginfo G__CalibrationManagerDictLN_TMemberInspector;
extern G__linked_taginfo G__CalibrationManagerDictLN_string;
extern G__linked_taginfo G__CalibrationManagerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__CalibrationManagerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CalibrationManagerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__CalibrationManagerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CalibrationManagerDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR;
extern G__linked_taginfo G__CalibrationManagerDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__CalibrationManagerDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CalibrationManagerDictLN_TTigFragment;
extern G__linked_taginfo G__CalibrationManagerDictLN_TChannel;
extern G__linked_taginfo G__CalibrationManagerDictLN_VirtualOdb;
extern G__linked_taginfo G__CalibrationManagerDictLN_CalibrationManager;
extern G__linked_taginfo G__CalibrationManagerDictLN_maplEintcOTChannelmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__CalibrationManagerDictLN_maplEstringcOTChannelmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTChannelmUgRsPgRsPgR;
extern G__linked_taginfo G__CalibrationManagerDictLN_CalibrationManagercLcLInfileOptions;

/* STUB derived class for protected member access */
